export default {
  ADMIN: {
    HOME: "/admin",
    PROFILE: "/admin/profile",
    CHANGEPASSWORD: "/admin/doi-mat-khau",
    SETTING: "/admin/cai-dat",
    SETTINGADD: "/admin/them-cai-dat",
    SPECIALIZE: "/admin/chuyen-mon",
    CERTIFICATES: "/admin/chung-chi",
    LOGIN: "/admin/dang-nhap",
    ACCOUNTLEVEL: "/admin/cap-do-tai-khoan",
    USER: "/admin/thanh-vien",
    USER_SPECIALIZEDETAILPT: "/admin/thanh-vien/chuyen-mon",
    COURSE_REQUEST: "/admin/khoa-hoc-yeu-cau",
    COURSE_REQUEST_STAGE: "/admin/khoa-hoc-yeu-cau/giai-doan",
    BILLINGS: "/admin/hoa-don",
    TRANSACTIONS: "/admin/giao-dich",
    COMPLAIN: "/admin/danh-sach-khieu-nai",
    BILL_PAY_FOR_PT: "/admin/thanh-toan-pt",
    BILL_COURSES_PT: "/admin/hoa-don-thanh-toan-pt",
    MANAGE_REVIEWS: "/admin/quan-ly-danh-gia-khoa-hoc",
    PERMISSION: "/admin/quan-li-quyen",
    ROLE: "/admin/quan-li-chuc-vu",
    ROLEADD: "/admin/them-chuc-vu",
    ROLEEDIT: "/admin/sua-chuc-vu",
    STUDENT_REGISTERED: "/admin/hoc-vien-da-dang-ky",
    CONTACT: "/admin/lien-he",
    REPLY_CONTACT: "/admin/tra-loi-mail",
  },

  PT: {
    HOME: "/pt",
    COURSES: "/pt/danh-sach-khoa-hoc",
    COURSESADD: "/pt/them-khoa-hoc",
    COURSESEDIT: "/pt/sua-khoa-hoc",
    COURSESEDITID: "/pt/sua-khoa-hoc/:id", //edit
    STAGE: "/pt/khoa-hoc",
    STAGES: "/pt/khoa-hoc/:id/giai-doan",
    STAGEADD: "/pt/khoa-hoc/:id/them-giai-doan",
    STAGEEDIT: "/pt/khoa-hoc/:id/sua-giai-doan/:idStage",
    SPECIALIZEDETAILPT: "/pt/chuyen-mon",
    CERTIFICATES_OF_SPECIALIZEDETAIL: "/pt/chuyen-mon/chung-chi",
    COURSES_PLAN: "/pt/khoa-hoc/:id/buoi-hoc/:idStage",
    COURSES_PLAN_ADD: "/pt/khoa-hoc/:id/buoi-hoc/:idStage/them-buoi-hoc",
    COURSES_PLAN_EDIT:
      "/pt/khoa-hoc/:id/giai-doan/:idStage/sua-buoi-hoc/:idPlan",
    PROFILE: "/pt/profile",
    CHANGEPASSWORD: "/pt/doi-mat-khau",
    STUDENT_MANAGER: "/pt/quan-ly-hoc-vien",
    SCHEDULE: "/pt/xep-lich/:id_course_student",
    SCHEDULES: "/pt/tat-ca-lich-day",
    SCHEDULEDAY: "/pt/lich-day-theo-ngay",
    PAYMENT_REQUEST: "/pt/yeu-cau-thanh-toan",
    BILL_COURSES: "/pt/hoa-don-thanh-toan",
    RESCHEDULE_COURSE: "/pt/buoi-hoc-can-xep-lai",
  },
  CLIENT: {
    HOME: "/",
    LISTPT: "/danh-sach-pt",
    PT_DETAIL: "/thong-tin-pt/:id",
    LISTCOURSE: "/danh-sach-khoa-hoc",
    COURSEDETAIL: "/khoa-hoc/:nameCourse/:id",
    TYPELOGIN: "/dang-nhap",
    LOGINPT: "/dang-nhap-pt",
    LOGINCUSTOMER: "/dang-nhap-khach-hang",
    REGISTERPT: "/dang-ky-pt",
    TYPEREGISTER: "/dang-ky",
    REGISTERCUSTUMER: "/dang-ky-khach-hang",
    PAYMENT_INVOICE: "/nap-tien/thong-bao",
    PAYMENT_INVOICE_REGISTER: "/hoa-don-dang-ki-hoc",
    COURSES_MANAGER: "/khach-hang/quan-ly-khoa-hoc",
    CONFIRM_COURSES: "/khach-hang/xac-nhan-lich-hoc",
    PROFILE: "/khach-hang",
    SCHEDULE: "/khach-hang/lich-hoc/:id",
    SCHEDULES: "/khach-hang/tat-ca-lich-hoc",
    SCHEDULEDAY: "/khach-hang/lich-hoc-theo-ngay",
    LESSONS: "/khach-hang/bai-hoc/:id_course_student",
    PAYMENT: "/khach-hang/nap-tien",
    PAYMENT_INVOICE_CUSTOMER: "/khach-hang/nap-tien/thong-bao",
    BILL_CUSTOMER: "/khach-hang/hoa-don",
    TRANSACTION_HISTORY: "/khach-hang/lich-su-giao-dich",
    RESET_PASS: "/lay-lai-mat-khau",
    CONTACT: "/lien-he",
    FORBIDDEN_PAGE: "/403",
    LIST_COMPLAIN: "/khach-hang/danh-sach-khieu-nai",
    PAGE_401: "/400",
    PROFILECUSTOM: "/khach-hang/thong-tin",
    CHANGEPASSWORD: "/khach-hang/doi-mat-khau",
  },
};
